force-app/main/default/objects/Lead/fields/TXT_CNPJ__c.field-meta.xml
<CustomField>
    <fullName>TXT_CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TXT_Nome_Fantasia__c.field-meta.xml
<CustomField>
    <fullName>TXT_Nome_Fantasia__c</fullName>
    <label>Nome Fantasia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TXT_Razao_Social__c.field-meta.xml
<CustomField>
    <fullName>TXT_Razao_Social__c</fullName>
    <label>Razão Social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TXT_situacaoCadastral__c.field-meta.xml
<CustomField>
    <fullName>TXT_situacaoCadastral__c</fullName>
    <label>Situaçcão Cadastral</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateLeadSituacaoCadastral.cls
public class UpdateLeadSituacaoCadastral implements Queueable {
    ID leadId;

    public UpdateLeadSituacaoCadastral(ID leadId) {
        this.leadId = leadId;
    }

    public void execute(QueueableContext context) {
        Lead lead = [SELECT TXT_CNPJ__c, TXT_Nome_Fantasia__c, TXT_Razao_Social__c, TXT_situacaoCadastral__c FROM Lead WHERE Id = :leadId];
        lead.TXT_situacaoCadastral__c = 'CNPJ nao ativo na Receita federal';
        update lead;
    }
}