force-app/main/default/objects/Opportunity/fields/DAT_Data_Fim__c.field-meta.xml
<CustomField>
    <fullName>DAT_Data_Fim__c</fullName>
    <label>Data Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DAT_Data_Inicio__c.field-meta.xml
<CustomField>
    <fullName>DAT_Data_Inicio__c</fullName>
    <label>Data Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FRM_Logotipo__c.field-meta.xml
<CustomField>
    <fullName>FRM_Logotipo__c</fullName>
    <formula>IMAGE(&apos;https://stage4-dev-ed--c.develop.vf.force.com/resource/1706470335000/Stage&apos;, &apos;LightLogo&apos;, 125, 200)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Logotipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PKL_novoCliente__c.field-meta.xml
<CustomField>
    <fullName>PKL_novoCliente__c</fullName>
    <label>Novo Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TXTL_Detalhamento_do_projeto__c.field-meta.xml
<CustomField>
    <fullName>TXTL_Detalhamento_do_projeto__c</fullName>
    <label>Detalhamento do projeto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FRM_Custo_total__c.field-meta.xml
<CustomField>
    <fullName>FRM_Custo_total__c</fullName>
    <formula>PricebookEntry.FRM_Custo__c *  Quantity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Custo total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FRM_Receita_Total__c.field-meta.xml
<CustomField>
    <fullName>FRM_Receita_Total__c</fullName>
    <formula>(ListPrice * Quantity)-FRM_Custo_total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receita Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_img__c.field-meta.xml
<CustomField>
    <fullName>Product_img__c</fullName>
    <formula>IMAGE(&quot;/sfc/servlet.shepherd/version/download/&quot; &amp; Product2.Product_Image_id__c, &quot;&quot;, 98, 115)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_img__c.field-meta.xml
<CustomField>
    <fullName>Product_img__c</fullName>
    <description>Esse campo formula reflete a imagem anexada no produto, através do campo Product_Image_ID__c e da logica embuida á ele.</description>
    <formula>IMAGE(&quot;/sfc/servlet.shepherd/version/download/&quot; &amp; Product_Image_id__c, &apos;image alternate text&apos;, 98, 115)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Opp_OrderController.cls
public class Opp_OrderController {
    public final Opportunity opportunity {get;set;}
    public final List<OpportunityLineItem> produtosDaOpp {get;set;}
    public Opp_OrderController(){
        String OpportunityId = getIdNaURL();
        opportunity = getOpp(OpportunityId);
        produtosDaOpp = getProdutosDaOpp(OpportunityId);
    }
    
    public String getIdNaURL(){
        return ApexPages.currentPage().getParameters().get('id');
    }
    
    public Opportunity getOpp(String OpportunityId){
        List<Opportunity> opportunities = [SELECT name, DAT_Data_Inicio__c, Amount, DAT_Data_Fim__c, TXTL_Detalhamento_do_projeto__c, PKL_novoCliente__c, FRM_Logotipo__c, CreatedDate

                               FROM Opportunity WHERE Id = :OpportunityId]; 
        return opportunities.get(0);
    }
    
    public List<OpportunityLineItem> getProdutosDaOpp(String OpportunityId){
        List<OpportunityLineItem> items = [SELECT Product2.Name, Quantity,
                                 Product2.ProductCode, UnitPrice, FRM_Custo_total__c,
                                 FRM_Receita_Total__c, Product_img__c
                                 FROM OpportunityLineItem WHERE OpportunityId = :OpportunityId
                                ];
      
        return items;
    }
}