force-app/main/default/objects/Opportunity/fields/DAT_Data_Fim__c.field-meta.xml
<CustomField>
    <fullName>DAT_Data_Fim__c</fullName>
    <label>Data Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DAT_Data_Inicio__c.field-meta.xml
<CustomField>
    <fullName>DAT_Data_Inicio__c</fullName>
    <label>Data Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FRM_Logotipo__c.field-meta.xml
<CustomField>
    <fullName>FRM_Logotipo__c</fullName>
    <formula>IMAGE(&apos;https://stage4-dev-ed--c.develop.vf.force.com/resource/1706470335000/Stage&apos;, &apos;LightLogo&apos;, 125, 200)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Logotipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PKL_novoCliente__c.field-meta.xml
<CustomField>
    <fullName>PKL_novoCliente__c</fullName>
    <label>Novo Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TXTL_Detalhamento_do_projeto__c.field-meta.xml
<CustomField>
    <fullName>TXTL_Detalhamento_do_projeto__c</fullName>
    <label>Detalhamento do projeto</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FRM_Custo_total__c.field-meta.xml
<CustomField>
    <fullName>FRM_Custo_total__c</fullName>
    <formula>PricebookEntry.FRM_Custo__c *  Quantity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Custo total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FRM_Receita_Total__c.field-meta.xml
<CustomField>
    <fullName>FRM_Receita_Total__c</fullName>
    <formula>(ListPrice * Quantity)-FRM_Custo_total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receita Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_img__c.field-meta.xml
<CustomField>
    <fullName>Product_img__c</fullName>
    <formula>IMAGE(&quot;/sfc/servlet.shepherd/version/download/&quot; &amp; Product2.Product_Image_id__c, &quot;&quot;, 98, 115)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_img__c.field-meta.xml
<CustomField>
    <fullName>Product_img__c</fullName>
    <description>Esse campo formula reflete a imagem anexada no produto, através do campo Product_Image_ID__c e da logica embuida á ele.</description>
    <formula>IMAGE(&quot;/sfc/servlet.shepherd/version/download/&quot; &amp; Product_Image_id__c, &apos;image alternate text&apos;, 98, 115)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/saveVfPdfCtrl.cls
public class saveVfPdfCtrl {
    public String MstrId{GET;SET;}
    public Opportunity oppObj{GET;SET;}
    
    public String PDFNo{GET;SET;}
    public String EFNo{GET;SET;}
    public BOOLEAN SHOW{GET;SET;}
    public BOOLEAN showpdf{GET;SET;}
    public ApexPages.PageReference page2{GET;SET;}
    public String baseURL{GET;SET;}
    public final Opportunity opportunity {get;set;}
    public final List<OpportunityLineItem> produtosDaOpp {get;set;}

    public PageReference Cancel() {
        PageReference Pdf = new PageReference('/'+MstrID);
        Pdf.setRedirect(true);
        return Pdf;
    }
    
    public saveVfPdfCtrl(ApexPages.StandardController Controller) {
        baseURL = Url.getOrgDomainURL().toExternalForm();
        MstrId = ApexPages.currentPage().getParameters().get('id');
        oppObj = [SELECT Id, Name, Email__c FROM Opportunity WHERE Id = :MstrId];
        String OpportunityId = getIdNaURL();
        produtosDaOpp = getProdutosDaOpp(OpportunityId);
        opportunity = getOpp(OpportunityId);
    }

    public String getIdNaURL() {
        return ApexPages.currentPage().getParameters().get('id');
    }
    
    public Opportunity getOpp(String OpportunityId) {
        List<Opportunity> opportunities = [SELECT name, DAT_Data_Inicio__c, Amount, DAT_Data_Fim__c, 
                                           TXTL_Detalhamento_do_projeto__c, PKL_novoCliente__c, Email__c,
                                           FRM_Logotipo__c, CreatedDate
                               FROM Opportunity WHERE Id = :OpportunityId]; 
        return opportunities.get(0);
    }
    
    public List<OpportunityLineItem> getProdutosDaOpp(String OpportunityId) {
        List<OpportunityLineItem> items = [SELECT Product2.Name, Quantity,
                                 Product2.ProductCode, UnitPrice, FRM_Custo_total__c,
                                 FRM_Receita_Total__c, Product_img__c
                                 FROM OpportunityLineItem WHERE OpportunityId = :OpportunityId];
      
        return items;
    }

    public PageReference pdfAction() {
        PageReference savepage = Page.savePdfVp;
        savepage.getParameters().put('id', MstrId);
        Blob pdfBlob;

        if (!Test.isRunningTest()) {
            pdfBlob = savepage.getContent(); // Gera o PDF BLOB
        } else { 
            pdfBlob = Blob.valueOf('Test');
        }

        List<ContentDocumentLink> notesattch = [SELECT Id, ContentDocument.Title, LinkedEntityId 
                                               FROM ContentDocumentLink 
                                               WHERE LinkedEntityId = :MstrId 
                                               ORDER BY ContentDocument.Title ASC];

        if (notesattch.size() > 0) {
            String title = notesattch[0].ContentDocument.Title;
            List<String> titleSplit = title.split('R');
            String FinalTitle = 'PO' + notesattch.size();

            PDFNo = FinalTitle;

            ContentVersion conVer = new ContentVersion();
            conVer.ContentLocation = 'S'; // TO USE S specify this document IS IN Salesforce, TO USE E FOR external files
            conVer.PathOnClient = FinalTitle + '.pdf'; 
            conVer.Title = FinalTitle; 
            conVer.VersionData = pdfBlob;
            INSERT conVer;  
    
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :conVer.Id].ContentDocumentId;
    
            ContentDocumentLink conDocLink = new ContentDocumentLink();
            conDocLink.LinkedEntityId = MstrId;
            conDocLink.ContentDocumentId = conDoc; 
            conDocLink.shareType = 'V';
            INSERT conDocLink;
            UPDATE oppObj;
    
            PageReference pageRef = new PageReference(baseURL + '/lightning/r/Opportunity/' + 
                                                      System.currentPageReference().getParameters().get('id') + '/view');
            pageRef.setRedirect(true);

            Messaging.SingleEmailMessage emailToSend = sendEmail();
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{emailToSend});
            
            return pageRef;
        } else {
            return null;
        }
    }

    public Messaging.SingleEmailMessage sendEmail() {
        PageReference pdfPage = Page.savePdfVp;
        pdfPage.getParameters().put('id', MstrId);
        Blob pdfBlob;

        if (!Test.isRunningTest()) {
            pdfBlob = pdfPage.getContent(); // Gera o PDF
        } else {
            pdfBlob = Blob.valueOf('Test');
        }

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        email.setSubject('Assunto do E-mail');  // Substitua pelo assunto desejado
        email.setToAddresses(new List<String>{opportunity.Email__c});  // Usa o endereço de e-mail da oportunidade
        email.setPlainTextBody('Corpo do e-mail');  // Substitua pelo corpo do e-mail desejado

        Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
        attachment.setFileName('NomeDoArquivo.pdf');  // Substitua pelo nome desejado para o anexo
        attachment.setBody(pdfBlob);
        email.setFileAttachments(new List<Messaging.EmailFileAttachment>{attachment});

        return email;
    }
}